//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManage.Api_data
{
    using System;
    using System.Collections.Generic;
    
    public partial class barcodedata
    {
        public long ID { get; set; }
        public string Barcode { get; set; }
        public Nullable<long> Rid { get; set; }
        public Nullable<long> Rcol { get; set; }
        public Nullable<long> pid { get; set; }
    
        public virtual product product { get; set; }
        public virtual Rack Rack { get; set; }
        public virtual Rackcolumn Rackcolumn { get; set; }
    }
}
